### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by chufnagel** [ctrliq/ascender#26]
### Please confirm the following

- [X] I have checked the [current issues](https://github.com/ctrliq/ascender/issues) for duplicates.
- [X] I understand that Ascender is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello - it looks like the link in the repo description is broken. https://ciq.com/products/ascender-automation/ goes to a 404 page - it looks like the updated link should be https://ciq.com/products/ascender/

### Ascender version

N/A

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

Attempt to go to the CIQ product page for Ascender

### Expected results

I am taken to the CIQ product page for Ascender

### Actual results

I am taken to a 404 page

### Additional information

Screenshot of link currently in repo description: ![Screenshot 2024-06-24 at 2 45 39 PM](https://github.com/ctrliq/ascender/assets/927009/84129bd0-0d22-4109-8545-8eddf552c6bc)
Correct link: https://ciq.com/products/ascender/

**Comment by cigamit** [comment]
This was resolved a while back.  Thanks for submitting.
