### ISSUE TITLE
Documentation for installation and configuration?

### ISSUE THREAD

**Issue by linuxcube** [ctrliq/ascender#8]
### Please confirm the following

- [X] I have checked the [current issues](https://github.com/ctrliq/ascender/issues) for duplicates.
- [X] I understand that Ascender is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Where is the docuemtnation describing the installaion and configuration for Rocky 8.x? PLease advise.

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

unable to find installation documents in the main github repo.

### Current results

not avaiable.

### Sugested feature result

Please make the Docs accesible as soon as possible.

**Comment by cigamit** [comment]
We will be releasing an installer soon that will cover installation.  As this is based off the upstream AWX, it is possible to install it via the same method as the upstream and just substitute our image url for theirs in your manifest.
